name: Next.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: ESLint Check
        run: npm run lint

      # - name: Run tests
      #  run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Set this in your repo secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Set this in your repo secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Set this in your repo secrets
          # Below are optional parameters
          vercel-args: '--prod' # Deploy to production
          working-directory: './' # Directory to deploy
  